version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=tarpaulin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - my-network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - my-network
      
  node:
    build: .
    container_name: api
    environment:
      - MONGO_DB_NAME=tarpaulin
      - MONGO_HOST=mongo
      - MONGO_USER=root
      - MONGO_PASSWORD=hunter2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALLOW_EMPTY_PASSWORD=yes
    restart: on-failure
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:8000"
    networks:
      - my-network

networks:
  my-network:
